chore: Base architecture, DI, Navigation, Login added
customerio/RemoteHabits-Android pull request #32
Opened 2022-01-10 11:55 UTC by Shahroz16

2022-01-10 20:24 UTC, levibostian approved these changes

2022-01-10 20:24 UTC, levibostian commented on app/src/main/java/io/customer/remotehabits/ui/login/LoginRoute.kt
> +            color = Color.Red,
We should probably move this into the theme? Sure, the color might always be red no matter if using dark or light mode but I believe using `Color.Red` would be creating tech debt if we ever, for example, want to change the shade of the red in dark mode to a darker color shade. 

Another benefit to not using `Color.Red` but instead using a theme color reference such as `RHTheme.color.errorText` is the color is now named using [semantic colors](https://developer.android.com/guide/topics/ui/look-and-feel/themes#versus) so if we wanted to change the error text color in the future to blue, we just need to change the color in the theme instead of having to change all code references from `Color.Red` to `Color.Blue`.

2022-01-10 20:24 UTC, levibostian commented on app/src/main/java/io/customer/remotehabits/ui/navigation/RHNavigation.kt
> +    object Dashboard : Screen("dashboard")
Do we see any problems with using hard-coded strings here? Compared to using an enum or sealed class instead to encapsulate the string?

2022-01-10 20:24 UTC, levibostian commented on app/src/main/res/values/colors.xml
> +    <color name="yellow">#FFFAE5</color>
Reason for using `Color.kt` and this color resource file? Can we just use 1?

2022-01-11 13:15 UTC, Shahroz16 commented on app/src/main/java/io/customer/remotehabits/ui/login/LoginRoute.kt
> +            contentDescription = null,
Actually, this is one picture itself, but because it's very large and is a kind of footer for scalability reasons, both iOS and Android have gotten the asserted and made the picture ourselves. 
So not sure how valuable will be it to give description to each icon within the whole picture.

2022-01-11 13:15 UTC, Shahroz16 commented on app/src/main/java/io/customer/remotehabits/ui/login/LoginRoute.kt
> +    backgroundColor: Color = Color.White,
Good point, the background was while in both modes in design hence the hardcode, but ideally should add it in the theme itself incase we decide to change it.

2022-01-11 13:15 UTC, Shahroz16 commented on app/src/main/java/io/customer/remotehabits/ui/navigation/RHNavigation.kt
> +    object Dashboard : Screen("dashboard")
I think this is okay because this is the source of all our `Screen` routes are present here in this sealed class. And everyplace else is referring to this class when referring to any screen route.

2022-01-11 13:15 UTC, Shahroz16 commented on app/src/main/res/values/colors.xml
> +    <color name="yellow">#FFFAE5</color>
Now Android, recommends using the `Splash` screen via `styles` and not making a dedicated activity with random delay and in order to access these colors from styles we need to have them in color xml resource.

2022-01-11 16:38 UTC, levibostian commented on app/src/main/java/io/customer/remotehabits/data/models/User.kt
> +data class User(
I am fine with either choice. I do believe that `SharedPreferences` would be the easiest and we can always migrate to a database later on if we feel it's needed. 

As far as scalability, sharedprefs are key/value storage. If we need to add more user attributes, we just add a new key/value pair entry? I don't see that as a scalability problem?

2022-01-11 16:43 UTC, levibostian commented on app/src/main/java/io/customer/remotehabits/di/DatabaseModule.kt
> +    @Singleton
I believe when those docs you quoted say *scope*, they mean scope as-in the scope of the module. `@InstallIn(XXX)` where XXX defines the scope of the module which defines the scope of the dependencies of that module. They are defining scope in regards to where the dependencies will live in memory, not how long they will live in memory. You can install a module in the global Application scope. You can install a module in an Activity scope, etc. 

By looking at each of the dependencies in all of the Hilt modules, I don't think that *any* of the dependencies need to be singletons. The code seems like it will behave as intended without the use of singletons.

2022-01-11 16:43 UTC, levibostian commented on app/src/main/java/io/customer/remotehabits/di/DatabaseModule.kt
> +    @Singleton
Let's continue the conversation [here](https://github.com/customerio/RemoteHabits-Android/pull/32#discussion_r781492110) but just remember that if we propose changes to be done, the changes are also applied here and everywhere relevant.

2022-01-11 16:45 UTC, levibostian commented on app/src/main/java/io/customer/remotehabits/di/RepositoryModule.kt
> +object RepositoryModule {
I am asking if this change would work:
1. Delete this module class. 
2. Change `UserRepositoryImpl` to:

```kt
class UserRepositoryImpl @Inject constructor(...) {
```

2022-01-11 16:49 UTC, levibostian commented on app/src/main/java/io/customer/remotehabits/ui/login/LoginRoute.kt
> +            contentDescription = null,
Agree that it's not valuable to give a description of each icon in the while picture.

2022-01-11 16:52 UTC, levibostian commented on app/src/main/res/values/colors.xml
> +    <color name="yellow">#FFFAE5</color>
Can we modify `Color.kt` to reference these xml values? 

```kt
class Colors {
   val PrimaryBackground(R.color.primary_background)
}
```

Or if we can't do that, do we make a comment in this xml file stating that this xml file only exists for the splash screen and therefore only needs to contain the colors for the splash screen? 

I want to avoid having to maintain colors in 2 different places in the project. That seems error-prone as it's easy to forget to update both with a color change.

2022-01-11 16:54 UTC, levibostian reviewed
After a second look at the PR, I'm going to refrain from approving the PR until the Hilt module Singleton discussion is done. 

Singletons should be used as little as possible so I want to pause the PR until that is conversation is resolved.

2022-01-11 16:55 UTC, levibostian requested changes
After a second look at the PR, I'm going to refrain from approving the PR until the Hilt module Singleton discussion is done.

Singletons should be used as little as possible so I want to pause the PR until that is conversation is resolved.

2022-01-11 18:28 UTC, Shahroz16 commented on app/src/main/java/io/customer/remotehabits/data/models/User.kt
> +data class User(
Scalability as in, if we have to fetch user properties, we will be needing fetch values for `X` many attributes.

2022-01-11 18:28 UTC, Shahroz16 commented on app/src/main/java/io/customer/remotehabits/di/DatabaseModule.kt
> +    @Singleton
If you look into the table at the end of [doc](https://dagger.dev/hilt/components.html#component-bindings), you will see find in order to provide for the scope of application we need it to be `Singleton`. 

For example the Module is question is Database module, why would we want its instance to be created for an activity? while we could still access that instance from other sources such as Services and others etc.

2022-01-11 18:28 UTC, Shahroz16 commented on app/src/main/java/io/customer/remotehabits/di/RepositoryModule.kt
> +object RepositoryModule {
I don't think it will, also I tried your recommendation and it responds back with an error 

`UserRepository cannot be provided without an @Provides-annotated method.`

So if we intend our ViewModels to be dependent on Repositories rather than Repository implementation, we will have to add a `Provider` using a Module.

2022-01-11 18:28 UTC, Shahroz16 commented on app/src/main/res/values/colors.xml
> +    <color name="yellow">#FFFAE5</color>
I don't think this would be possible since accessing we won't be able to access constants present in Java/Kotlin file from styles class. I'll add the comment for visibility.

2022-01-11 18:35 UTC, Shahroz16 commented on app/src/main/java/io/customer/remotehabits/di/DatabaseModule.kt
> +    @Singleton
Tried looking for industry practice, and this hilt sample [application](https://github.com/googlecodelabs/android-hilt/blob/solution/app/src/main/java/com/example/android/hilt/di/DatabaseModule.kt) by google also does expose Database as a `Singleton` scoped module

2022-01-11 20:35 UTC, levibostian commented on app/src/main/java/io/customer/remotehabits/di/DatabaseModule.kt
> +    @Singleton
Taking a step back away from Hilt/Dagger or from the `DatabaseModule`: Singletons should be used sparingly in a code base. They should only be used when there is a use case for using them and even then, it's a good idea to ask yourself if there is a better design pattern to use for the code to avoid having to use a singleton. I think we can all agree with that. That's where my concern originates for this PR suggestion is the use of singletons and the need for using them. 

I just looked over all of Dagger Modules in this PR again. I can now see a point in making [`NavigationManager`](https://github.com/customerio/RemoteHabits-Android/blob/3483fb1db4110c4cfa232325be2ee5899a3c98cd/app/src/main/java/io/customer/remotehabits/ui/navigation/NavigationManager.kt) a singleton because it contains a `MutableStateFlow` property that is shared by the application. I understand that the [Repository classes](https://github.com/customerio/RemoteHabits-Android/blob/3483fb1db4110c4cfa232325be2ee5899a3c98cd/app/src/main/java/io/customer/remotehabits/di/RepositoryModule.kt) are scoped to ViewModel because Repository classes and ViewModel classes work closely together (However, does that mean that I cannot use a Repository in a Service? Because Repositories are now only scoped to ViewModels?). 

I don't understand why the [sample application](https://github.com/googlecodelabs/android-hilt/blob/solution/app/src/main/java/com/example/android/hilt/di/DatabaseModule.kt) makes the database instance a singleton but that's based on me not using Room for many months and forgetting it's setup. I don't see a problem with [making the database a Singleton](https://github.com/customerio/RemoteHabits-Android/blob/3483fb1db4110c4cfa232325be2ee5899a3c98cd/app/src/main/java/io/customer/remotehabits/di/DatabaseModule.kt#L19). 

Lastly we get to the Dao. I do not see a need to [make this a singleton](https://github.com/customerio/RemoteHabits-Android/blob/3483fb1db4110c4cfa232325be2ee5899a3c98cd/app/src/main/java/io/customer/remotehabits/di/DatabaseModule.kt#L32). I don't see a use case in mind that makes it necessary.

2022-01-11 20:39 UTC, levibostian commented on app/src/main/java/io/customer/remotehabits/di/RepositoryModule.kt
> +object RepositoryModule {
Ah, yes! [I forgot that we use an interface for the UserRepository](https://github.com/customerio/RemoteHabits-Android/blob/3483fb1db4110c4cfa232325be2ee5899a3c98cd/app/src/main/java/io/customer/remotehabits/data/repositories/UserRepository.kt#L8-L12). We would need to use `@Provides` if we use an interface. 

What is the reason for using the interface `UserRepository`? Do we need the interface?

2022-01-11 20:40 UTC, levibostian commented on app/src/main/java/io/customer/remotehabits/di/NavigationModule.kt
> +    @Singleton
Thank you. As explained [here](https://github.com/customerio/RemoteHabits-Android/pull/32#discussion_r782505864), I see the point of singleton here now.

2022-01-11 20:45 UTC, levibostian commented on app/src/main/java/io/customer/remotehabits/data/models/User.kt
> +data class User(
Ah, I see. The iOS app today has to [make X number of functions for X number of attributes](https://github.com/customerio/RemoteHabits-iOS/blob/142d79801d36f6b53df52118dc8bd6e80584a65d/Remote%20Habits/Manager/UserManager.swift). 

If we were building an app a few years ago, I would push harder to suggest using `SharedPreferences` but making async background queries against a database today is much less boilerplate thanks to coroutines. We do have to create database migrations each time we want to add an attribute to the User table but even that problem doesn't exist because of Room automatic migrations! 

I am OK with using a database for storing user data.

2022-01-11 22:26 UTC, Shahroz16 commented on app/src/main/java/io/customer/remotehabits/di/DatabaseModule.kt
> +    @Singleton
`Singletons` should definitely be only used when necessary, but in the case of Network and DB it becomes a requirement because we don't want to create multiple instances and handle closing/opening of connection or get into any race conditions. 

`DAO` doesn't need to be `Singleton`, I would update it. 

Regarding the scope being `viewmodel` for the repository, yup, ideally we won't be exposing Repository classes to Services either. They would have direct access to DAOs or view models and communicate.

2022-01-13 18:01 UTC, Shahroz16 commented on app/src/main/java/io/customer/remotehabits/di/RepositoryModule.kt
> +object RepositoryModule {
For the sole reason of modulatory, when we want to test, we can provide a mocked implementation for the User respository.

2022-01-13 21:42 UTC, levibostian approved these changes

2022-01-13 21:43 UTC, merged